### ISSUE TITLE
Fees to Claim Vesting Balance Too High

### ISSUE THREAD

**Issue by landry314** [bitshares/bsips#32] opened 2017-10-01 12:13 UTC
When I try to claim vesting balances on my lifetime account I get:

Quantity | 29.2415 BTS
Fee | 24.27935 BTS

The quantity is slowly creeping up because it has only been trading and transferring fees recently. When I bought some accounts, this 24 BTS fee was negligible but now it prevents me from claiming my vesting balance.

Has this fee just not been updated in a long time? Maybe it is an oversight from a time when 24 BTS had much less value.

**Comment by abitmore** [comment] 2017-11-27 10:08
This concern is valid. Someone please write a formal BSIP so we can proceed.

**Comment by pmconrad** [comment] 2019-04-24 14:50
Closing since committee is actively maintaining fees.

**Comment by abitmore** [comment] 2019-04-24 15:41
The issue is about the cashback mechanism, not the committee.

**Comment by pmconrad** [comment] 2019-04-25 07:00
It's about the fees, no?

**Comment by abitmore** [comment] 2019-08-22 16:21
No further discussion about the mechanism, closing. BTW the fees have been reduced, see https://github.com/bitshares/committee-tools/pull/9.

**Closed by abitmore** 2019-08-22 16:21 UTC
