### ISSUE TITLE
bsip28 lacks of determinate technical specification

### ISSUE THREAD

**Issue by abitmore** [bitshares/bsips#40] opened 2017-11-11 20:13 UTC
* The specification of BSIP's should be determinate, wording like "Possibly allow" is not acceptable.
* I don't think committee should have the right to terminate a worker proposal.

**Comment by wmbutler** [comment] 2017-11-12 03:54
I tend to agree. The BSIP was intended to be a working document.

**Comment by pmconrad** [comment] 2019-04-24 15:16
Also see #77 . Closing here for a more focused discussion.

**Closed by pmconrad** 2019-04-24 15:16 UTC
